version: '3.8'
services:
  chatbot:
    image: $DOCKER_HUB_USERNAME/kibwa-chatbot:latest
    container_name: kibwa-chatbot
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./chat_logs:/app/chat_logs
      - ./member_information:/app/member_information
      - ./emotion_data:/app/emotion_data
      - ./profanity_data:/app/profanity_data
    env_file:
      - .env