version: '3.8'

services:
  app:
    image: yootaesung/kibwa-chatbot:latest
    container_name: kibwa-chatbot
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./chatbot/member_information:/app/chatbot/member_information
      - ./chatbot/emotion_data:/app/chatbot/emotion_data
      - ./chatbot/profanity_data:/app/chatbot/profanity_data
      - ./chatbot/chat_logs:/app/chatbot/chat_logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
