version: '3.8'

services:
  app:
    image: ${DOCKER_HUB_USERNAME}/kibwa-chatbot:latest
    container_name: kibwa-chatbot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /work/kibwa_project/chatbot/member_information:/app/chatbot/member_information
      - /work/kibwa_project/chatbot/chat_logs:/app/chatbot/chat_logs
    env_file:
      - .env
