name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  EC2_HOST: ${{ secrets.HOST }}
  EC2_USERNAME: ${{ secrets.USERNAME }}
  EC2_KEY: ${{ secrets.KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "--- Pulling Latest Code ---"
            cd /path/to/project
            git pull origin main
            
            echo "--- Stopping and Removing Old Container ---"
            docker stop chatbot_app || true
            docker rm chatbot_app || true
            
            echo "--- Building and Running New Container ---"
            docker build -t chatbot_app .
            
            docker run -d \
              --restart always \
              --name chatbot_app \
              -p 8000:8000 \
              -v /path/to/chat_logs:/app/chat_logs \
              -v /path/to/emotion_data:/app/emotion_data \
              -v /path/to/member_information:/app/member_information \
              -v /path/to/profanity_data:/app/profanity_data \
              --network=host \
              chatbot_app
